export default {
    bg_intro_step_1: require('./intro/bg_intro_step_1.png'),
    bg_intro_step_2: require('./intro/bg_intro_step_2.png'),
    bg_intro_step_3: require('./intro/bg_intro_step_3.png'),
    bg_intro_step_4: require('./intro/bg_intro_step_4.png'),
    img_intro_step_1: require('./intro/img_intro_step_1.png'),
    img_intro_step_2: require('./intro/img_intro_step_2.png'),
    img_intro_step_3: require('./intro/img_intro_step_3.png'),
    img_intro_step_4: require('./intro/img_intro_step_4.png'),
    bg_login_1: require('./bg_login_1.png'),
    facebook_logo: require('./facebook_logo.png'),
    google_logo: require('./google_logo.png'),
    back: require('./back.png'),
    heart: require('./heart.png'),
    options: require('./options.png'),
    picture: require('./picture.png'),
    profile: require('./profile.png'),
    send: require('./send.png'),
    user_chat: require('./user_chat.png'),
    search: require('./search.png'),
    line: require('./line.png'),
    plus: require('./plus.png'),
    expert_img: require('./expert_img.png'),
    edit: require('./edit.png'),

    modalLine: require('./modalLine.png'),
    optionsLine: require('./optionsLine.png'),
    feelings: {
        happy: require('./feelings/happy.png'),
        sad: require('./feelings/sad.png'),
        depression: require('./feelings/depression.png'),
        normal: require('./feelings/normal.png'),
        scared: require('./feelings/scared.png'),
        worry: require('./feelings/worry.png'),
        angry: require('./feelings/angry.png'),
    },
    line: require('./line.png'),
    user_avatar: require('./user_avatar.png'),
};
